"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Tile;
(function (Tile) {
    Tile["Man1"] = "man1";
    Tile["Man2"] = "man2";
    Tile["Man3"] = "man3";
    Tile["Man4"] = "man4";
    Tile["Man5"] = "man5";
    Tile["Man6"] = "man6";
    Tile["Man7"] = "man7";
    Tile["Man8"] = "man8";
    Tile["Man9"] = "man9";
    Tile["Pin1"] = "pin1";
    Tile["Pin2"] = "pin2";
    Tile["Pin3"] = "pin3";
    Tile["Pin4"] = "pin4";
    Tile["Pin5"] = "pin5";
    Tile["Pin6"] = "pin6";
    Tile["Pin7"] = "pin7";
    Tile["Pin8"] = "pin8";
    Tile["Pin9"] = "pin9";
    Tile["Sou1"] = "sou1";
    Tile["Sou2"] = "sou2";
    Tile["Sou3"] = "sou3";
    Tile["Sou4"] = "sou4";
    Tile["Sou5"] = "sou5";
    Tile["Sou6"] = "sou6";
    Tile["Sou7"] = "sou7";
    Tile["Sou8"] = "sou8";
    Tile["Sou9"] = "sou9";
    Tile["Ton"] = "ton";
    Tile["Nan"] = "nan";
    Tile["Sha"] = "sha";
    Tile["Pei"] = "pei";
    Tile["Haku"] = "haku";
    Tile["Hatsu"] = "hatsu";
    Tile["Chun"] = "chun";
})(Tile || (Tile = {}));
exports.default = Tile;
