export declare const Tile: {
    Man1: string;
    Man2: string;
    Man3: string;
    Man4: string;
    Man5: string;
    Man6: string;
    Man7: string;
    Man8: string;
    Man9: string;
    Pin1: string;
    Pin2: string;
    Pin3: string;
    Pin4: string;
    Pin5: string;
    Pin6: string;
    Pin7: string;
    Pin8: string;
    Pin9: string;
    Sou1: string;
    Sou2: string;
    Sou3: string;
    Sou4: string;
    Sou5: string;
    Sou6: string;
    Sou7: string;
    Sou8: string;
    Sou9: string;
    Ton: string;
    Nan: string;
    Sha: string;
    Pei: string;
    Haku: string;
    Hatsu: string;
    Chun: string;
};
export declare type Tile = typeof Tile[keyof typeof Tile];
