import { Tiles34Type } from './../types/tilesType';
import HandConfigType from './../types/handConfigType';
import Yaku from './yaku';
declare class YakuConfig {
    akaDora: Yaku;
    chankan: Yaku;
    chanta: Yaku;
    Chiitoitsu: Yaku;
    chinitsu: Yaku;
    dora: Yaku;
    doubleRiichi: Yaku;
    haitei: Yaku;
    honitsu: Yaku;
    honroutou: Yaku;
    houtei: Yaku;
    iipeikou: Yaku;
    ippatsu: Yaku;
    ittsuu: Yaku;
    junchan: Yaku;
    pinfu: Yaku;
    riichi: Yaku;
    rinshan: Yaku;
    ryanpeikou: Yaku;
    sanAnkou: Yaku;
    sanKantsu: Yaku;
    sanshoku: Yaku;
    sanshokuDoukou: Yaku;
    shousangen: Yaku;
    tanyao: Yaku;
    toitoi: Yaku;
    tsumo: Yaku;
    uraDora: Yaku;
    yakuhaiChun: Yaku;
    yakuhaiEast: Yaku;
    yakuhaiHaku: Yaku;
    yakuhaiHatsu: Yaku;
    yakuhaiNorth: Yaku;
    yakuhaiOfPlace: Yaku;
    yakuhaiOfRound: Yaku;
    yakuhaiSouth: Yaku;
    yakuhaiWest: Yaku;
    chiihou: Yaku;
    chinroutou: Yaku;
    chuurenPoutou: Yaku;
    daisangen: Yaku;
    daisuushii: Yaku;
    kokushiMusou: Yaku;
    renhou: Yaku;
    ryuuiisou: Yaku;
    shousuushii: Yaku;
    suuAnkou: Yaku;
    suuKantsu: Yaku;
    tenhou: Yaku;
    tsuuiisou: Yaku;
    constructor(tiles: Tiles34Type, handConfig: HandConfigType);
}
export default YakuConfig;
